using System.Collections.Generic;
using System.IO;


namespace GameEventSystem.CustomEditor
{
    /// <summary>
    /// Class that holds much of the constant information about where to save the EventIDList.cs file.
    /// </summary>
    public static class EventListFileManager
    {
        // Folder to save the EventIDList.cs file in
        public const string LIST_SAVE_PATH = "Assets/Plugins/GameEventSystem/EventWindow_DO_NOT_EDIT";
        // Folder to save the scriptable objects in
        public const string EVENT_SAVE_PATH = LIST_SAVE_PATH + "/Events";

        // File extensions for asset and meta data
        public const string ASSET_FILE_EXTENSION = ".asset";
        public const string META_FILE_EXTENSION = ".meta";

        // Name of the class/file name and the file's extension
        public const string EVENTID_LIST_CLASS_NAME = "EventIDList";
        private const string EVENTID_LIST_FILE_EXTENSION = ".cs";


        // Events that are currently in the EventIDList
        public static string[] CurrentEvents => currentEventsInTheList;
        private static string[] currentEventsInTheList = new string[0];
        // If the EventIDList is currently being constructed
        private static bool isBeingCreated = false;


        /// <summary>
        /// Gets a list of event names from the assets in the folder.
        /// </summary>
        /// <returns>List of event names from the file system.</returns>
        public static string[] GetListOfEventNames()
        {
            if (Directory.Exists(EVENT_SAVE_PATH))
            {
                string[] rawFileNames = Directory.GetFiles(EVENT_SAVE_PATH);
                string[] rawNonMetaFileNames = RemoveMetaFiles(rawFileNames);
                string[] fileNames = RemovePathsFromRawFileNames(rawNonMetaFileNames);
                return RemoveExtensionsFromFileNames(fileNames);
            }
            return new string[0];
        }
        /// <summary>
        /// Gets the path to the event asset with the given name.
        /// </summary>
        /// <param name="eventName">Name of the event to get the path of.</param>
        /// <returns>Path to the sriptable event.</returns>
        public static string GetEventAssetPath(string eventName)
        {
            return EVENT_SAVE_PATH + "/" + eventName + ASSET_FILE_EXTENSION;
        }
        /// <summary>
        /// Gets the full file path to the EventIDList2.cs.
        /// </summary>
        /// <returns>Full file path to EventIDList.cs with extension.</returns>
        public static string GetFullFilePath()
        {
            return LIST_SAVE_PATH + "/" + EVENTID_LIST_CLASS_NAME + EVENTID_LIST_FILE_EXTENSION;
        }
        public static void DeleteOldIDListFiles()
        {
            // Search for the event id list in the file system and delete any files that are not
            // where they should be.
            
        }

        /// <summary>
        /// Returns a copy of the given array, but with any meta files missing.
        /// </summary>
        /// <param name="rawFileNames">Array of file names to remove meta files from.</param>
        /// <returns>Array of file names with no meta files.</returns>
        public static string[] RemoveMetaFiles(string[] rawFileNames)
        {
            List<string> nonMetaFiles = new List<string>();
            for (int i = 0; i < rawFileNames.Length; ++i)
            {
                string curName = rawFileNames[i];
                if (curName[curName.Length - 1] != 'a')
                {
                    nonMetaFiles.Add(curName);
                }
            }
            return nonMetaFiles.ToArray();
        }

        /// <summary>
        /// Creates/updates the const static file with the event id's saved as const ints.
        /// </summary>
        public static void CreateFile()
        {
            if (isBeingCreated)
            {
                return;
            }
            isBeingCreated = true;

            UnityEngine.Debug.Log("CreatingFile");

            // Beginning and end of the file
            const string FILE_BEGIN_TEXT = "// DO NOT EDIT DIRECTLY. GENERATED BY InitializeEventList.cs" + "\r\r" +
            "public static class " + EVENTID_LIST_CLASS_NAME + "\r" +
            "{";
            const string FILE_END_TEXT = "}";

            // Generate lines to write for each event
            currentEventsInTheList = GetListOfEventNames();
            string[] eventConstLines = GenerateEventConstantLines(currentEventsInTheList);
            string[] writeLines = new string[eventConstLines.Length + 2];
            // First line is the begin text
            writeLines[0] = FILE_BEGIN_TEXT;
            // All other lines are the event constants
            for (int i = 0; i < eventConstLines.Length; ++i)
            {
                writeLines[i + 1] = "    " + eventConstLines[i];
            }
            // Last line is the end text
            writeLines[writeLines.Length - 1] = FILE_END_TEXT;

            // Check if the path exists
            if (!Directory.Exists(LIST_SAVE_PATH))
            {
                Directory.CreateDirectory(LIST_SAVE_PATH);
            }

            // Write to the file
            File.WriteAllLines(GetFullFilePath(), writeLines);

            isBeingCreated = false;
        }


        /// <summary>
        /// Creates and returns an array of strings that will serve as lines in the
        /// generated script to be public const ints.
        /// </summary>
        /// <returns>Array of strings that can be used as lines in the generated script.</returns>
        private static string[] GenerateEventConstantLines(string[] eventNames)
        {
            string[] eventLines = new string[eventNames.Length];
            for (int i = 0; i < eventLines.Length; ++i)
            {
                string eventName = eventNames[i];
                string eventID = eventName;
                eventLines[i] = "public const string " + eventName + " = \"" + eventID + "\";";
            }
            return eventLines;
        }

        /// <summary>
        /// Gets the file names (with extensions) from the full paths given.
        /// </summary>
        /// <param name="rawFileNames">Raw paths to the files.</param>
        /// <returns>Array of the file names.</returns>
        private static string[] RemovePathsFromRawFileNames(string[] rawFileNames)
        {
            string[] shorterNames = new string[rawFileNames.Length];
            for (int i = 0; i < rawFileNames.Length; ++i)
            {
                string curName = rawFileNames[i];
                int pathEndIndex = curName.LastIndexOf('\\');
                if (pathEndIndex == -1)
                {
                    pathEndIndex = curName.LastIndexOf('/');
                }
                shorterNames[i] = curName.Substring(pathEndIndex + 1);
            }
            return shorterNames;
        }
        /// <summary>
        /// Removes any extensions from the given file names. If a file has multiple extensions
        /// like .cs.meta it will only remove the .meta.
        /// </summary>
        /// <param name="fileNames">File names with extensions.</param>
        /// <returns>File names missing their extensions.</returns>
        private static string[] RemoveExtensionsFromFileNames(string[] fileNames)
        {
            string[] shorterNames = new string[fileNames.Length];
            for (int i = 0; i < fileNames.Length; ++i)
            {
                string curName = fileNames[i];
                int extStartIndex = curName.LastIndexOf('.');
                shorterNames[i] = curName.Substring(0, extStartIndex);
            }
            return shorterNames;
        }
    }
}
