// DO NOT EDIT DIRECTLY. GENERATED BY EventWindow.cspublic static class EventIDList{
    public const int Event1 = 0;
    public const int Event2 = 1;
    public const int Event3 = 2;
    public const int Event4 = 3;
    public const int Event5 = 4;
    public const int Event6 = 5;
    public const int Event7 = 6;
    public const int Event9 = 7;
}
