// DO NOT EDIT DIRECTLY. GENERATED BY InitializeEventList.cspublic static class EventIDList{
    public const string Alan = "Alan";
    public const string BenBen = "BenBen";
    public const string Eslis = "Eslis";
    public const string Marcus = "Marcus";
    public const string Misty = "Misty";
    public const string Tong = "Tong";
}
